### ISSUE TITLE
cannot specify '-o' with '-c', '-S' or '-E' with multiple files

### ISSUE THREAD

**Issue by Strit** [angerman/meson64-tools#1]
Thanks for the effort regarding this project, I am really looking forward to seeing it released.

Since the documentation is still a little "missing" on how to build this, I just threw myself out in a `make all` to see how it's going.

But in the ssl parts I get a couple of these errors:
```
cc: fatal error: cannot specify '-o' with '-c', '-S' or '-E' with multiple files
```
With gcc 10.2 on aarch64 ofcourse.

it's entirely possible that I am missing dependencies of some sort, but it's hard to know without the documentation.

Keep up the good work. Will keep an eye on this project, in the hopes of one day being able to build a mainline amlogic uboot on the aarch64 device itself.

**Comment by angerman** [comment]
I'm not really sure where that comes from.  I've been using `nix` to build this:
```
[angerman@aarch64]$ git clone https://github.com/angerman/meson64-tools.git
Cloning into 'meson64-tools'...
remote: Enumerating objects: 1462, done.
remote: Counting objects: 100% (1462/1462), done.
remote: Compressing objects: 100% (1071/1071), done.
remote: Total 1462 (delta 348), reused 1455 (delta 341), pack-reused 0
Receiving objects: 100% (1462/1462), 4.28 MiB | 9.17 MiB/s, done.
Resolving deltas: 100% (348/348), done.
[angerman@aarch64]$ cd meson64-tools/
[angerman@aarch64:meson64-tools]$ nix build
[angerman@aarch64:meson64-tools]$ ls result/bin
bl2sig  bl30sig  bl3sig  bootmk  pkg
```
and use the tools with the following `Makefile` to produce the file boot image:
```
bl30.pkg: data/bl30.bin data/bl301.bin
	pkg --type bl30 --output $@ $^

bl2.pkg: data/bl2.bin data/acs.bin
	pkg --type bl2 --output $@ $^

bl30.30sig: bl30.pkg
	bl30sig --input $< --output $@

bl30.3sig: bl30.30sig
	bl3sig  --input $< --output $@

bl31.3sig: data/bl31.img
	bl3sig  --input $< --output $@

bl33.3sig: $(UBOOT)
	bl3sig  --input $< --output $@

bl2.2sig: bl2.pkg
	bl2sig  --input $< --output $@

u-boot.bin: bl2.2sig bl30.3sig bl31.3sig bl33.3sig data/ddr4_1d.fw data/ddr4_2d.fw data/ddr3_1d.fw data/piei.fw data/lpddr4_1d.fw data/lpddr4_2d.fw data/diag_lpddr4.fw data/aml_ddr.fw
	bootmk --output $@ \
	  --bl2 bl2.2sig --bl30 bl30.3sig --bl31 bl31.3sig --bl33 bl33.3sig \
	  --ddrfw1 data/ddr4_1d.fw   --ddrfw2 data/ddr4_2d.fw   --ddrfw3 data/ddr3_1d.fw     --ddrfw4 data/piei.fw \
	  --ddrfw5 data/lpddr4_1d.fw --ddrfw6 data/lpddr4_2d.fw --ddrfw7 data/diag_lpddr4.fw --ddrfw8 data/aml_ddr.fw

.phony: install

install: u-boot.bin
	install -m 644 u-boot.bin $(PREFIX)/u-boot.bin
	@echo ""
	@echo ">> Write the image to SD with"
	@echo ">> =========================="
	@echo ">> DEV=/dev/mmcblkX"
	@echo ">> dd if=fip/u-boot.bin of=\$$DEV conv=fsync,notrunc bs=512 seek=1"
	@echo ""
```

it is using `ghc-8.3.0`; not sure if that makes much of a difference. 

Can't really tell from the single line error :-/

**Comment by Strit** [comment]
Yeah, I understand that. :) But it's the only error I get.

It was just to tell you, that some documentation on how to build it might be needed. :smile:

**Comment by Strit** [comment]
Got it to build. Had to unset my CFLAGS and LDFLAGS from my system.

Sadly the resulting mainline uboot does not boot. :disappointed:
