### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [angerman/meson64-tools#2]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPLv3 or AGPLv3 license so that others are encouraged to contribute changes back to your project.

**Comment by matwey** [comment]
Could you please choose some LICENSE for the code? For instance, the license is required to create RPM package.

**Comment by L-as** [comment]
bump

**Comment by considerate** [comment]
@angerman Is this piece of software open source (if so, under what license) or do you reserve all rights?
